// Package main implements the fence CLI.
package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"

	"github.com/Use-Tusk/fence/internal/config"
	"github.com/Use-Tusk/fence/internal/fencelog"
	"github.com/Use-Tusk/fence/internal/importer"
	"github.com/Use-Tusk/fence/internal/platform"
	"github.com/Use-Tusk/fence/internal/sandbox"
	"github.com/Use-Tusk/fence/internal/templates"
	"github.com/spf13/cobra"
	"golang.org/x/sys/unix"
	"golang.org/x/term"
)

// Build-time variables (set via -ldflags)
var (
	version   = "dev"
	buildTime = "unknown"
	gitCommit = "unknown"
)

var (
	debug                 bool
	monitor               bool
	settingsPath          string
	templateName          string
	listTemplates         bool
	cmdString             string
	exposePorts           []string
	serviceExecutionModel string
	exposeHostPaths       []string
	exposeHostPathsRW     []string
	shellMode             string
	shellLogin            bool
	fenceLogFile          string
	forceNewSession       bool
	exitCode              int
	showVersion           bool
	linuxFeatures         bool
)

func main() {
	if path := strings.TrimSpace(os.Getenv(fencelog.EnvVar)); path != "" {
		if err := fencelog.AppendLogFile(path); err != nil {
			fmt.Fprintf(os.Stderr, "[fence] Warning: failed to open fence log file %q: %v\n", path, err)
		}
	}

	// Check for internal helper modes used inside/generated by the sandbox.
	// This must be checked before cobra to avoid flag conflicts
	if len(os.Args) >= 2 && os.Args[1] == "--landlock-apply" {
		runLandlockWrapper()
		return
	}
	if len(os.Args) >= 2 && os.Args[1] == "--linux-argv-exec-run" {
		exitCode, err := sandbox.RunLinuxArgvExecRunnerFromEnv()
		if err != nil {
			fencelog.Printf("[fence:linux] %v\n", err)
		}
		os.Exit(exitCode)
	}
	if len(os.Args) >= 2 && os.Args[1] == "--linux-argv-exec-shim" {
		exitCode, err := sandbox.RunLinuxArgvExecShim(os.Args[2:])
		if err != nil {
			fencelog.Printf("[fence:linux] %v\n", err)
		}
		os.Exit(exitCode)
	}
	if len(os.Args) >= 2 && os.Args[1] == claudePreToolUseMode {
		if err := runClaudePreToolUseMode(); err != nil {
			fencelog.Printf("[fence:hooks] %v\n", err)
			os.Exit(2)
		}
		return
	}
	if len(os.Args) >= 2 && os.Args[1] == cursorPreToolUseMode {
		if err := runCursorPreToolUseMode(); err != nil {
			fencelog.Printf("[fence:hooks] %v\n", err)
			os.Exit(2)
		}
		return
	}
	if len(os.Args) >= 2 && os.Args[1] == opencodePreToolUseMode {
		if err := runOpencodePreToolUseMode(); err != nil {
			fencelog.Printf("[fence:hooks] %v\n", err)
			os.Exit(2)
		}
		return
	}

	rootCmd := &cobra.Command{
		Use:   "fence [flags] -- [command...]",
		Short: "Run commands in a sandbox with network and filesystem restrictions",
		Long: `fence is a command-line tool that runs commands in a sandboxed environment
with network and filesystem restrictions.

By default, all network access is blocked. Fence first looks for a
fence.jsonc (preferred) or fence.json file in the current directory or any
parent directory. If none is found, it falls back to
$XDG_CONFIG_HOME/fence/fence.{jsonc,json} on Linux (typically
~/.config/fence/) or ~/.config/fence/fence.{jsonc,json} on macOS. You can
also pass a settings file with --settings or use a built-in template with
--template.

Examples:
  fence curl https://example.com          # Will be blocked (no domains allowed)
  fence -- curl -s https://example.com    # Use -- to separate fence flags from command
  fence -c "echo hello && ls"             # Run with shell expansion
  fence --settings config.json npm install
  fence -t npm-install npm install        # Use built-in npm-install template
  fence -t ai-coding-agents -- agent-cmd  # Use AI coding agents template
  fence -p 3000 -c "npm run dev"          # Expose port 3000 for inbound connections
  fence --shell user -c "nvim"            # Use validated $SHELL for command execution
  fence --list-templates                  # Show available built-in templates
  fence config show                       # Inspect the active config chain and merged JSON

Configuration file format:
{
  "network": {
    "allowedDomains": ["github.com", "*.npmjs.org"],
    "deniedDomains": []
  },
  "filesystem": {
    "denyRead": [],
    "allowWrite": ["."],
    "denyWrite": []
  },
  "command": {
    "deny": ["git push", "npm publish"]
  }
}`,
		RunE:          runCommand,
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.ArbitraryArgs,
	}

	rootCmd.Flags().BoolVarP(&debug, "debug", "d", false, "Enable debug logging")
	rootCmd.Flags().BoolVarP(&monitor, "monitor", "m", false, "Monitor and log sandbox violations (macOS: log stream, all: proxy denials)")
	rootCmd.Flags().StringVarP(&settingsPath, "settings", "s", "", "Path to settings file (default: nearest project fence.jsonc/fence.json or OS config path)")
	rootCmd.Flags().StringVarP(&templateName, "template", "t", "", "Use built-in template (e.g., ai-coding-agents, npm-install)")
	rootCmd.Flags().BoolVar(&listTemplates, "list-templates", false, "List available templates")
	rootCmd.Flags().StringVarP(&cmdString, "c", "c", "", "Run command string directly (like sh -c)")
	rootCmd.Flags().StringArrayVarP(&exposePorts, "port", "p", nil, "Expose port for inbound connections (can be used multiple times)")
	rootCmd.Flags().StringVar(&serviceExecutionModel, "service-execution-model", "in-sandbox",
		"How the sandboxed service binds its exposed ports: 'in-sandbox' (default; fence sets up a reverse bridge) or 'on-host' (an external daemon like docker/podman binds the port outside the sandbox netns; no reverse bridge)")
	rootCmd.Flags().StringArrayVar(&exposeHostPaths, "expose-host-path", nil, "Expose a host file/directory at the same path inside the sandbox (read-only). Can be used multiple times.")
	rootCmd.Flags().StringArrayVar(&exposeHostPathsRW, "expose-host-path-rw", nil, "Expose a host file/directory at the same path inside the sandbox (read-write). Can be used multiple times.")
	rootCmd.Flags().StringVar(&shellMode, "shell", sandbox.ShellModeDefault, "Shell mode for command execution: default (bash) or user ($SHELL)")
	rootCmd.Flags().BoolVar(&shellLogin, "shell-login", false, "Run shell as login shell (-lc). Use with --shell user for shell init compatibility")
	rootCmd.Flags().StringVar(&fenceLogFile, "fence-log-file", "", "Write Fence monitor/debug logs to this file while keeping command output on its normal streams")
	rootCmd.Flags().BoolVar(&forceNewSession, "force-new-session", false, "Linux only: force bubblewrap --new-session even for interactive PTY sessions")
	rootCmd.Flags().BoolVarP(&showVersion, "version", "v", false, "Show version information")
	rootCmd.Flags().BoolVar(&linuxFeatures, "linux-features", false, "Show available Linux security features and exit")

	rootCmd.Flags().SetInterspersed(true)

	rootCmd.AddCommand(newImportCmd())
	rootCmd.AddCommand(newConfigCmd())
	rootCmd.AddCommand(newHooksCmd())
	rootCmd.AddCommand(newCompletionCmd(rootCmd))

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		exitCode = 1
	}
	_ = fencelog.CloseLogFile()
	os.Exit(exitCode)
}

func runCommand(cmd *cobra.Command, args []string) error {
	resolvedFenceLogFile := ""
	if strings.TrimSpace(fenceLogFile) != "" {
		absPath, err := filepath.Abs(fenceLogFile)
		if err != nil {
			return fmt.Errorf("failed to resolve fence log file %q: %w", fenceLogFile, err)
		}
		resolvedFenceLogFile = absPath
		if err := fencelog.SetLogFile(resolvedFenceLogFile); err != nil {
			return fmt.Errorf("failed to open fence log file %q: %w", resolvedFenceLogFile, err)
		}
	}

	if showVersion {
		fmt.Printf("fence - lightweight, container-free sandbox for running untrusted commands\n")
		fmt.Printf("  Version: %s\n", version)
		fmt.Printf("  Built:   %s\n", buildTime)
		fmt.Printf("  Commit:  %s\n", gitCommit)
		return nil
	}

	if linuxFeatures {
		sandbox.PrintLinuxFeatures()
		return nil
	}

	if listTemplates {
		printTemplates()
		return nil
	}

	var command string
	switch {
	case cmdString != "":
		command = cmdString
	case len(args) > 0:
		command = sandbox.ShellQuote(args)
	default:
		return fmt.Errorf("no command specified. Use -c <command> or provide command arguments")
	}

	if debug {
		fencelog.Printf("[fence] Command: %s\n", command)
	}

	var ports []int
	for _, p := range exposePorts {
		port, err := strconv.Atoi(p)
		if err != nil || port < 1 || port > 65535 {
			return fmt.Errorf("invalid port: %s", p)
		}
		ports = append(ports, port)
	}

	var execModel sandbox.ServiceExecutionModel
	switch strings.ToLower(strings.TrimSpace(serviceExecutionModel)) {
	case "", "in-sandbox":
		execModel = sandbox.ServiceBindsInSandbox
	case "on-host":
		execModel = sandbox.ServiceBindsOnHost
	default:
		return fmt.Errorf("invalid --service-execution-model %q (expected 'in-sandbox' or 'on-host')", serviceExecutionModel)
	}

	if debug && len(ports) > 0 {
		modelName := "in-sandbox"
		if execModel == sandbox.ServiceBindsOnHost {
			modelName = "on-host"
		}
		fencelog.Printf("[fence] Exposing ports: %v (execution model: %s)\n", ports, modelName)
	}

	// Validate shell mode early to fail before proxy/sandbox initialization.
	if _, _, err := sandbox.ResolveExecutionShell(shellMode, shellLogin); err != nil {
		return fmt.Errorf("invalid shell options: %w", err)
	}

	activeConfig, err := loadActiveConfigAudit("", settingsPath, templateName)
	if err != nil {
		return err
	}

	cfg := activeConfig.Config
	if debug {
		switch activeConfig.Root.Kind {
		case config.ResolutionStepKindTemplate:
			fencelog.Printf("[fence] Using template: %s\n", activeConfig.Root.Name)
		case config.ResolutionStepKindFile:
			fencelog.Printf("[fence] Using config file: %s\n", activeConfig.Root.Path)
		case config.ResolutionStepKindDefault:
			fencelog.Printf("[fence] No config found at %s, using default (block all network)\n", activeConfig.Root.Path)
		}
	}

	cfg = applyCLIConfigOverrides(cmd, cfg, forceNewSession)

	manager := sandbox.NewManager(cfg, debug, monitor)
	manager.SetService(sandbox.ServiceOptions{
		ExposedPorts:   ports,
		ExecutionModel: execModel,
	})
	manager.SetShellOptions(shellMode, shellLogin)
	for _, p := range exposeHostPaths {
		if err := manager.ExposeHostPath(p, false); err != nil {
			return fmt.Errorf("invalid --expose-host-path %q: %w", p, err)
		}
	}
	for _, p := range exposeHostPathsRW {
		if err := manager.ExposeHostPath(p, true); err != nil {
			return fmt.Errorf("invalid --expose-host-path-rw %q: %w", p, err)
		}
	}
	defer manager.Cleanup()

	if err := manager.Initialize(); err != nil {
		return fmt.Errorf("failed to initialize sandbox: %w", err)
	}

	var logMonitor *sandbox.LogMonitor
	if monitor {
		logMonitor = sandbox.NewLogMonitor(sandbox.GetSessionSuffix())
		if logMonitor != nil {
			if err := logMonitor.Start(); err != nil {
				fencelog.Printf("[fence] Warning: failed to start log monitor: %v\n", err)
			} else {
				defer logMonitor.Stop()
			}
		}
	}

	sandboxedCommand, err := manager.WrapCommand(command)
	if err != nil {
		return presentWrapCommandError(err)
	}

	if debug {
		fencelog.Printf("[fence] Sandboxed command: %s\n", sandboxedCommand)
	}

	hardenedEnv := sandbox.GetHardenedEnv()
	if resolvedFenceLogFile != "" {
		hardenedEnv = upsertEnv(hardenedEnv, fencelog.EnvVar, resolvedFenceLogFile)
	}
	if debug {
		if stripped := sandbox.GetStrippedEnvVars(os.Environ()); len(stripped) > 0 {
			fencelog.Printf("[fence] Stripped dangerous env vars: %v\n", stripped)
		}
	}

	execCmd := exec.Command("sh", "-c", sandboxedCommand) //nolint:gosec // sandboxedCommand is constructed from user input - intentional
	execCmd.Env = hardenedEnv

	// On Linux, PTY relay is only enabled for interactive sessions to avoid
	// surprising behavior changes (e.g., piping output through fence). When PTY
	// relay is active, the Linux wrapper can keep bwrap in the current session
	// so the inner shell retains normal job control.
	usePTY := cfg != nil &&
		cfg.AllowPty &&
		platform.Detect() == platform.Linux &&
		term.IsTerminal(int(os.Stdin.Fd())) && // #nosec G115 - fd fits in int on all supported platforms
		term.IsTerminal(int(os.Stdout.Fd())) // #nosec G115 - fd fits in int on all supported platforms

	// When stdin is a terminal, place the child in its own process group so
	// we can hand it terminal foreground control after Start(). This allows
	// interactive shells (e.g. "fence bash") to call tcsetpgrp() and enable
	// job control. Without this, bash prints:
	//   "cannot set terminal process group: Operation not permitted"
	//   "no job control in this shell"
	isTTY := term.IsTerminal(int(os.Stdin.Fd())) // #nosec G115 - fd fits in int on all supported platforms
	configureHostTTYChildProcessGroup(execCmd, isTTY, usePTY)

	if !usePTY {
		execCmd.Stdin = os.Stdin
		execCmd.Stdout = os.Stdout
		execCmd.Stderr = os.Stderr
	}

	cleanup, startErr := startCommand(execCmd, usePTY)
	if startErr != nil {
		return fmt.Errorf("failed to start command: %w", startErr)
	}
	defer cleanup()

	// Give the child process group terminal foreground control. We do this
	// from the parent because only the current foreground process group can
	// call tcsetpgrp. We ignore SIGTTOU so we don't get stopped when we
	// later reclaim the foreground (at that point we'll be in the background
	// process group).
	if shouldManageHostTTYForeground(isTTY, usePTY) && execCmd.Process != nil {
		stdinFd := int(os.Stdin.Fd()) // #nosec G115 - fd fits in int on all supported platforms

		savedFgPgrp, err := unix.IoctlGetInt(stdinFd, unix.TIOCGPGRP)
		if err != nil {
			if debug {
				fencelog.Printf("[fence] Warning: failed to get foreground pgrp: %v\n", err)
			}
		} else {
			childPid := execCmd.Process.Pid
			childPgrp, err := syscall.Getpgid(childPid)
			if err != nil {
				childPgrp = childPid // fallback: Setpgid with Pgid=0 sets pgid=pid
			}

			signal.Ignore(syscall.SIGTTOU)
			if err := unix.IoctlSetPointerInt(stdinFd, unix.TIOCSPGRP, childPgrp); err != nil {
				if debug {
					fencelog.Printf("[fence] Warning: failed to set child as foreground: %v\n", err)
				}
			}
			defer func() {
				_ = unix.IoctlSetPointerInt(stdinFd, unix.TIOCSPGRP, savedFgPgrp)
				signal.Reset(syscall.SIGTTOU)
			}()
		}
	}

	// Start Linux monitors (eBPF tracing for filesystem violations)
	var linuxMonitors *sandbox.LinuxMonitors
	if monitor && execCmd.Process != nil {
		linuxMonitors, _ = sandbox.StartLinuxMonitor(execCmd.Process.Pid, sandbox.LinuxSandboxOptions{
			Monitor: true,
			Debug:   debug,
			UseEBPF: true,
		})
		if linuxMonitors != nil {
			defer linuxMonitors.Stop()
		}
	}

	// Note: Landlock is NOT applied here because:
	// 1. The sandboxed command is already running (Landlock only affects future children)
	// 2. Proper Landlock integration requires applying restrictions inside the sandbox
	// For now, filesystem isolation relies on bwrap mount namespaces.
	// Landlock code exists for future integration (e.g., via a wrapper binary).

	// Wait for command to finish
	if err := execCmd.Wait(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			// Set exit code but don't os.Exit() here - let deferred cleanup run
			exitCode = exitErr.ExitCode()
			return nil
		}
		return fmt.Errorf("command failed: %w", err)
	}

	return nil
}

func presentWrapCommandError(err error) error {
	var commandBlockedErr *sandbox.CommandBlockedError
	if errors.As(err, &commandBlockedErr) {
		return err
	}

	var sshBlockedErr *sandbox.SSHBlockedError
	if errors.As(err, &sshBlockedErr) {
		return err
	}

	return fmt.Errorf("failed to wrap command: %w", err)
}

func upsertEnv(env []string, key, value string) []string {
	prefix := key + "="
	for i, entry := range env {
		if strings.HasPrefix(entry, prefix) {
			env[i] = prefix + value
			return env
		}
	}
	return append(env, prefix+value)
}

func applyCLIConfigOverrides(cmd *cobra.Command, cfg *config.Config, forceNewSessionValue bool) *config.Config {
	if cfg == nil {
		cfg = config.Default()
	}
	if cmd.Flags().Changed("force-new-session") {
		value := forceNewSessionValue
		cfg.ForceNewSession = &value
	}
	return cfg
}

func startCommand(execCmd *exec.Cmd, usePTY bool) (func(), error) {
	if usePTY {
		return startCommandWithPTY(execCmd)
	}
	return startCommandWithSignalProxy(execCmd)
}

func configureHostTTYChildProcessGroup(execCmd *exec.Cmd, isTTY bool, usePTY bool) {
	if !shouldManageHostTTYForeground(isTTY, usePTY) {
		return
	}
	execCmd.SysProcAttr = &syscall.SysProcAttr{
		Setpgid: true,
		Pgid:    0, // child gets its own process group (pgid = child pid)
	}
}

func shouldManageHostTTYForeground(isTTY bool, usePTY bool) bool {
	return isTTY && !usePTY
}

func startCommandWithSignalProxy(execCmd *exec.Cmd) (func(), error) {
	if err := execCmd.Start(); err != nil {
		return nil, err
	}
	// Outer fence does not pgrp-broadcast on the 2nd signal: bwrap is
	// not always placed in its own pgrp here (only when there is a
	// controlling TTY; see configureHostTTYChildProcessGroup), so a
	// pgrp send could either be a no-op or hit our own group.
	stop := (&sandbox.SignalForwarder{Cmd: execCmd}).Start()
	return stop, nil
}

// newImportCmd creates the import subcommand.
func newImportCmd() *cobra.Command {
	var (
		claudeMode bool
		inputFile  string
		outputFile string
		saveFlag   bool
		forceFlag  bool
		extendTmpl string
		noExtend   bool
	)

	cmd := &cobra.Command{
		Use:   "import",
		Short: "Import settings from other tools",
		Long: `Import permission settings from other tools and convert them to fence config.

Currently supported sources:
  --claude    Import from Claude Code settings

By default, imports extend the "code" template which provides sensible defaults
for network access (npm, GitHub, LLM providers) and filesystem protections.
Use --no-extend for a minimal config, or --extend to choose a different template.

Examples:
  # Preview import (prints JSON to stdout)
  fence import --claude

  # Save to the default config path
  #   Linux: $XDG_CONFIG_HOME/fence/fence.json (typically ~/.config/fence/fence.json)
  #   macOS: ~/.config/fence/fence.json
  fence import --claude --save

  # Save to a specific output file
  fence import --claude -o ./fence.json

  # Import from a specific Claude Code settings file
  fence import --claude -f ~/.claude/settings.json --save

  # Import without extending any template (minimal config)
  fence import --claude --no-extend --save

  # Import and extend a different template
  fence import --claude --extend local-dev-server --save`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if !claudeMode {
				return fmt.Errorf("no import source specified. Use --claude to import from Claude Code")
			}

			opts := importer.DefaultImportOptions()
			if noExtend {
				opts.Extends = ""
			} else if extendTmpl != "" {
				opts.Extends = extendTmpl
			}

			result, err := importer.ImportFromClaude(inputFile, opts)
			if err != nil {
				return fmt.Errorf("failed to import Claude settings: %w", err)
			}

			for _, warning := range result.Warnings {
				fencelog.Printf("Warning: %s\n", warning)
			}
			if len(result.Warnings) > 0 {
				fencelog.Println()
			}

			// Determine output destination
			var destPath string
			if saveFlag {
				destPath = config.DefaultConfigPath()
			} else if outputFile != "" {
				destPath = outputFile
			}

			if destPath != "" {
				if !forceFlag {
					if _, err := os.Stat(destPath); err == nil {
						fmt.Printf("File %q already exists. Overwrite? [y/N] ", destPath)
						reader := bufio.NewReader(os.Stdin)
						response, _ := reader.ReadString('\n')
						response = strings.TrimSpace(strings.ToLower(response))
						if response != "y" && response != "yes" {
							fmt.Println("Aborted.")
							return nil
						}
					}
				}

				if err := os.MkdirAll(filepath.Dir(destPath), 0o750); err != nil {
					return fmt.Errorf("failed to create config directory: %w", err)
				}

				if err := importer.WriteConfig(result.Config, destPath); err != nil {
					return err
				}
				fmt.Printf("Imported %d rules from %s\n", result.RulesImported, result.SourcePath)
				fmt.Printf("Written to %q\n", destPath)
			} else {
				// Print clean JSON to stdout, helpful info to stderr (don't interfere with piping)
				data, err := importer.MarshalConfigJSON(result.Config)
				if err != nil {
					return fmt.Errorf("failed to marshal config: %w", err)
				}
				fmt.Println(string(data))
				if result.Config.Extends != "" {
					fencelog.Printf("\n# Extends %q - inherited rules not shown\n", result.Config.Extends)
				}
				fencelog.Printf("# Imported %d rules from %s\n", result.RulesImported, result.SourcePath)
				fencelog.Printf("# Use --save to write to the default config path\n")
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(&claudeMode, "claude", false, "Import from Claude Code settings")
	cmd.Flags().StringVarP(&inputFile, "file", "f", "", "Path to settings file (default: ~/.claude/settings.json for --claude)")
	cmd.Flags().StringVarP(&outputFile, "output", "o", "", "Output file path")
	cmd.Flags().BoolVar(&saveFlag, "save", false, "Save to the default config path")
	cmd.Flags().BoolVarP(&forceFlag, "force", "y", false, "Overwrite existing file without prompting")
	cmd.Flags().StringVar(&extendTmpl, "extend", "", "Template to extend (default: code)")
	cmd.Flags().BoolVar(&noExtend, "no-extend", false, "Don't extend any template (minimal config)")
	cmd.MarkFlagsMutuallyExclusive("extend", "no-extend")
	cmd.MarkFlagsMutuallyExclusive("save", "output")

	return cmd
}

// newConfigCmd creates config-related subcommands.
func newConfigCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "config",
		Short: "Manage fence configuration",
	}
	cmd.AddCommand(newConfigInitCmd())
	cmd.AddCommand(newConfigShowCmd())
	return cmd
}

// newCompletionCmd creates the completion subcommand for shell completions.
func newCompletionCmd(rootCmd *cobra.Command) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "completion [bash|zsh|fish|powershell]",
		Short: "Generate shell completion scripts",
		Long: `Generate shell completion scripts for fence.

Examples:
  # Bash (load in current session)
  source <(fence completion bash)

  # Zsh (load in current session)
  source <(fence completion zsh)

  # Fish (load in current session)
  fence completion fish | source

  # PowerShell (load in current session)
  fence completion powershell | Out-String | Invoke-Expression

To persist completions, redirect output to the appropriate completions
directory for your shell (e.g., /etc/bash_completion.d/ for bash,
${fpath[1]}/_fence for zsh, ~/.config/fish/completions/fence.fish for fish).
`,
		DisableFlagsInUseLine: true,
		ValidArgs:             []string{"bash", "zsh", "fish", "powershell"},
		Args:                  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			switch args[0] {
			case "bash":
				return rootCmd.GenBashCompletionV2(os.Stdout, true)
			case "zsh":
				return rootCmd.GenZshCompletion(os.Stdout)
			case "fish":
				return rootCmd.GenFishCompletion(os.Stdout, true)
			case "powershell":
				return rootCmd.GenPowerShellCompletionWithDesc(os.Stdout)
			default:
				return fmt.Errorf("unsupported shell: %s", args[0])
			}
		},
	}
	return cmd
}

// printTemplates prints all available templates to stdout.
func printTemplates() {
	fmt.Println("Available templates:")
	fmt.Println()
	for _, t := range templates.List() {
		fmt.Printf("  %-20s %s\n", t.Name, t.Description)
	}
	fmt.Println()
	fmt.Println("Usage: fence -t <template> <command>")
	fmt.Println("Example: fence -t code -- code")
}

// runLandlockWrapper runs in "wrapper mode" inside the sandbox.
// It applies Landlock restrictions and then execs the user command.
// Usage: fence --landlock-apply [--debug] -- <command...>
// Config is passed via FENCE_CONFIG_JSON environment variable.
func runLandlockWrapper() {
	// Parse arguments: --landlock-apply [--debug] -- <command...>
	args := os.Args[2:] // Skip "fence" and "--landlock-apply"

	var debugMode bool
	var cmdStart int

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--debug":
			debugMode = true
		case "--":
			cmdStart = i + 1
			goto parseCommand
		default:
			// Assume rest is the command
			cmdStart = i
			goto parseCommand
		}
	}

parseCommand:
	if cmdStart >= len(args) {
		fencelog.Printf("[fence:landlock-wrapper] Error: no command specified\n")
		os.Exit(1)
	}

	command := args[cmdStart:]

	if debugMode {
		fencelog.Printf("[fence:landlock-wrapper] Applying Landlock restrictions\n")
	}

	// Only apply Landlock on Linux
	if platform.Detect() == platform.Linux {
		// Load config from environment variable (passed by parent fence process)
		var cfg *config.Config
		if configJSON := os.Getenv("FENCE_CONFIG_JSON"); configJSON != "" {
			cfg = &config.Config{}
			if err := json.Unmarshal([]byte(configJSON), cfg); err != nil {
				if debugMode {
					fencelog.Printf("[fence:landlock-wrapper] Warning: failed to parse config: %v\n", err)
				}
				cfg = nil
			}
		}
		if cfg == nil {
			cfg = config.Default()
		}

		// Get current working directory for relative path resolution
		cwd, _ := os.Getwd()

		// Apply Landlock restrictions
		err := sandbox.ApplyLandlockFromConfig(cfg, cwd, nil, debugMode)
		if err != nil {
			if debugMode {
				fencelog.Printf("[fence:landlock-wrapper] Warning: Landlock not applied: %v\n", err)
			}
			// Continue without Landlock - bwrap still provides isolation
		} else if debugMode {
			fencelog.Printf("[fence:landlock-wrapper] Landlock restrictions applied\n")
		}
	}

	// Find the executable
	execPath, err := exec.LookPath(command[0])
	if err != nil {
		fencelog.Printf("[fence:landlock-wrapper] Error: command not found: %s\n", command[0])
		os.Exit(127)
	}

	if debugMode {
		fencelog.Printf("[fence:landlock-wrapper] Exec: %s %v\n", execPath, command[1:])
	}

	// Sanitize environment (strips LD_PRELOAD, etc.)
	hardenedEnv := sandbox.FilterDangerousEnv(os.Environ())

	// Exec the command (replaces this process)
	err = syscall.Exec(execPath, command, hardenedEnv) //nolint:gosec
	if err != nil {
		fencelog.Printf("[fence:landlock-wrapper] Exec failed: %v\n", err)
		os.Exit(1)
	}
}
